apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamsight-eventhubs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: streamsight-eventhubs
    spec:
      containers:
      - name: console
        image: streamsight/console
        ports:
        - containerPort: 4000
        env:
        - name: service
          value: "eventhubs"
        - name: connectionString
          value: ""
        - name: eventHubName
          value: ""
        - name: consumerGroup
          value: "$Default"