kind: Service
apiVersion: v1
metadata:
  name: streamsight-service-kafka
spec:
  selector:
    app: streamsight-kafka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer