apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamsight-kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: streamsight-kafka
    spec:
      containers:
      - name: console
        image: streamsight/console
        ports:
        - containerPort: 4000
        env:
        - name: service
          value: "kafka"
        - name: connectionString
          value: ""
        - name: topic
          value: ""